name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        brew cask install xquartz
        
        ln -s /opt/X11/include/X11 /usr/local/include/X11
        export CFLAGS=-I/opt/X11/include
        xcode-select --install
        
        pip install ueberzug
