name: master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        brew cask install xquartz
        
        git clone https://github.com/XQuartz/quartz-wm.git
        cd quartz-wm
        ACLOCAL="aclocal -I /opt/X11/share/aclocal" autoreconf -fvi
        PKG_CONFIG_PATH=/opt/X11/share/pkgconfig:/opt/X11/lib/pkgconfig ./configure --prefix=/opt/X11
        make
        cd ..
        
        pip install ueberzug
